name: Fetch patrons and commit JSON

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18.14.2

    - name: Install dependencies
      run: npm ci

    - name: Run custom npm script
      run: npm run get-patrons
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        SERVER_NAME: ${{ vars.SERVER_NAME }}
        ROLE_NAME: ${{ vars.ROLE_NAME }}

    - name: Set up Git and commit changes
      run: |
        git config user.name "GitHub Actions"
        git config user.email "github-actions@users.noreply.github.com"
        git add -A
        git diff --quiet && git diff --staged --quiet || git commit -m "Update generated files"

    - name: Push changes
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}